In [79]:
#!pip install numpy

In [80]:
import numpy as np

# Numpy Array

# 1D array 
a = np.array([1,2,3])
print("a=> ", a, a.shape, a.dtype)

#2D array 
b = np.array([[1.5, 2, 3],[4, 5, 6]], dtype=float)
print("b=> ", b, b.shape)

#3D array
c = np.array([[(1.5, 2, 3),(4, 5,6)],[(3,2,1),(4,5,6)]], dtype=float) # by default it's float
print("c=> ", c, c.shape, c.dtype) 


a=>  [1 2 3] (3,) int64
b=>  [[1.5 2.  3. ]
 [4.  5.  6. ]] (2, 3)
c=>  [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]] (2, 2, 3) float64


In [81]:
# Initializing Placeholders 
print("np.zeros((3,4)) =>\n", np.zeros((3,4))) # numpy with 3x4 array with zeros
print("np.ones((2,3,4), dtype=np.int16) =>\n", np.ones((2,3,4), dtype=np.int16)) # this is 3D array with ones. 2 x (3x4 matrix) i.e. two 3X4 matrix
print("np.linspace(0, 2, 9) =>\n", np.linspace(0, 2, 9)) # 9 item between 0 and 2 with equal spacing, 0 and 2 inclusive. 
print("np.full((2,2), 7) =>\n", np.full((2,2), 7)) # get 2x2 matrix filled with 7
print("identity matrix 2X2 =>\n", np.eye(2)) # give index 
print("random values =>\n", np.random.random((2,2))) # 2x2 matrix with random vlaues between 0 and 1.
print("empty in np =>\n", np.empty((3,2))) # empty values

np.zeros((3,4)) =>
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
np.ones((2,3,4), dtype=np.int16) =>
 [[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
np.linspace(0, 2, 9) =>
 [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
np.full((2,2), 7) =>
 [[7 7]
 [7 7]]
identity matrix 2X2 =>
 [[1. 0.]
 [0. 1.]]
random values =>
 [[0.46254525 0.44998202]
 [0.24975595 0.15682563]]
empty in np =>
 [[1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]
 [1.39069238e-309 1.39069238e-309]]


In [82]:
# IO operations
# Saving and loading numpy file on disk
np.save('my_array_a', a) # saves in disk as my_array_a.npy file, we can load this later
np.savez('save_npz.npz', a, b) # save a and b values

# Loading values
t = np.load('my_array_a.npy') # load numpy array from file and the load to variable t.
print("t=>", t)

a1, b1 = np.load('save_npz.npz')
print("a1=>", a1, "b1=>", b1)

t=> [1 2 3]
a1=> arr_0 b1=> arr_1


In [83]:
# Saving and loading text file
# np.loadtxt('textfilename.txt')
# np.genfromtxt('./data/data.csv', delimiter=',')
# np.savetxt('myarray.txt', a, delimiter=" ")

In [84]:
# data types in numpy
np.int16
np.float32
np.complex
np.bool
np.object
np.string_
np.unicode_

/var/folders/qh/416mh9qd4f7b91j59rcp2hmh0000gn/T/ipykernel_1822/3604115808.py:4: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex
/var/folders/qh/416mh9qd4f7b91j59rcp2hmh0000gn/T/ipykernel_1822/3604115808.py:5: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool
/var/folders/qh/416mh9qd4f7b91j59rcp2hmh0000gn/T/ipykernel_1822

numpy.str_

Inspecting the array

In [85]:
# Inspecting the array
# shape
print("a.shape=>\n", a.shape)
# length
print("len(a)=> \n", len(a)) # for 1D
print(len(b), len(c)) # for 2D and 3D its 2

# ndim number of array dimensions
print("a.ndim=>\n", a.ndim) # 1
print("b.ndim=>\n", b.ndim) # 2
print("c.ndim=>\n", c.ndim) # 3

# size : number of array elements
print("a.size=>\n", a.size)

# dtype data type of array element
print("a.dtype=>\n", a.dtype)
print("b.dtype=>\n", b.dtype)
print("c.dtype=>\n", c.dtype)
print("b.dtype.name=>\n", b.dtype.name)

# npvar.astype(dtype) e.g. b.astype(int)
converted_b = b.astype(int) # it converted without changing the original value. 
print(converted_b, converted_b.dtype)
print(b, b.dtype) # this will still be original


a.shape=>
 (3,)
len(a)=> 
 3
2 2
a.ndim=>
 1
b.ndim=>
 2
c.ndim=>
 3
a.size=>
 3
a.dtype=>
 int64
b.dtype=>
 float64
c.dtype=>
 float64
b.dtype.name=>
 float64
[[1 2 3]
 [4 5 6]] int64
[[1.5 2.  3. ]
 [4.  5.  6. ]] float64


Asking For help or information

In [86]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


Array Manipulation (Addition, subtraction, multiplication, divison, comparison, aggregation, copying array, sorting arry, subset, slicing and indexing)

In [87]:
# Arithmetics 
# Subtraction
print("a=>", a, "b=>", b, )
print("\n")
g1 = a-b
g2 = np.subtract(a, b)
print(g1, g1==g2)

# Addition
h1 = a + b
h2 = np.add(a,b)
print("\nh1=>", h1, "\n comp=>", h1==h2)

# Multiplication
m1 = a * b
m2 = np.multiply(a, b)
print(m1, m1==m2)


# Divison
d1 = a/b
d2 = np.divide(a, b)
print(d1, d1==d2)


# Some more mathematical functions
print(np.exp(b)) # exponentiation by element 
print(np.sqrt(b)) # get square root
print(np.sin(a)) # sin
print(np.cos(a)) # cos
print(np.log(a)) # element wise natural logarithm 
dt1, dt2 = np.array([1,2,3]), np.array([4,5,6]) # res: 1*4 + 2*5 + 3*6 = 32
print("dt1.dot(dt2)=>", dt1.dot(dt2)) # dotproduct 

a=> [1 2 3] b=> [[1.5 2.  3. ]
 [4.  5.  6. ]]


[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]] [[ True  True  True]
 [ True  True  True]]

h1=> [[2.5 4.  6. ]
 [5.  7.  9. ]] 
 comp=> [[ True  True  True]
 [ True  True  True]]
[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]] [[ True  True  True]
 [ True  True  True]]
[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]] [[ True  True  True]
 [ True  True  True]]
[[  4.48168907   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
[[1.22474487 1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.69314718 1.09861229]
dt1.dot(dt2)=> 32


In [88]:
# Comparison
print(a == b) # element wise comparison
print(a < 2) # also element wise comparison and return the result in array
np.array_equal(a,b) # Array wise comparison

[[False  True  True]
 [False False False]]
[ True False False]


False

### Aggregation Functions

In [89]:
# Aggregations functions
print(a.sum()) # sum
print(a.min()) #min
print(a.max()) #max
print(b.max(axis=0)) # maximum value of array row
print(b.cumsum(axis=1)) # cululative sum of the elemnets
print(b.mean()) # median
print(np.median(b)) # median # this does not work


6
1
3
[4. 5. 6.]
[[ 1.5  3.5  6.5]
 [ 4.   9.  15. ]]
3.5833333333333335
3.5


### Copying Array

In [90]:
# Copyting array
print("a=>", a)
print("b=>", b)

a=> [1 2 3]
b=> [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [91]:
h=a.view() # create the view of the array with the same data
print("h=>", h)
h[0]= 3.3
print("h:", h, "a:", a) # original a also changes


cpy = np.copy(a) # create a copy of the array
print("cpy=>", cpy)
cpy[0] = 5
print("cpy:", cpy, "a:", a) # no change to original a value.

h = a.copy() # create a deep copy of the array
print("h:", h, "a:", a)


h=> [1 2 3]
h: [3 2 3] a: [3 2 3]
cpy=> [3 2 3]
cpy: [5 2 3] a: [3 2 3]
h: [3 2 3] a: [3 2 3]


### Sorting Array

In [92]:
print("before : a:", a, "\n\nc:", c)
a.sort() # sort an array
c.sort(axis=0)  # this is not clear here yet

print("after a:", a, "\n\nc:", c)

before : a: [3 2 3] 

c: [[[1.5 2.  3. ]
  [4.  5.  6. ]]

 [[3.  2.  1. ]
  [4.  5.  6. ]]]
after a: [2 3 3] 

c: [[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]


In [93]:
print("b:", b)
b.sort(axis=0) # not entirely clear
print("b:", b)

b: [[1.5 2.  3. ]
 [4.  5.  6. ]]
b: [[1.5 2.  3. ]
 [4.  5.  6. ]]


### Subsetting, Slicing, Indexing

In [94]:
# subsetting
print("a:", a, "\n\nb:",b, "\nc:",c)
print(a[2]) # select the element at the 2nd index.

print(b[1,2]) # select the element at row 1 and column 2 ; same as b[1][2]
print(b[1][2]) # same 6.0

# Slicing
print(a[0:2]) # select element at index 0 and 1. 
print(b[0:2, 1]) # select element in 0 and 1 from column 1;
print("b[:1]=>",b[:1]) # select all items at row 0.
print(c[1,...]) # same as [1, :,:]
print("a[::-1]=>", a[::-1]) # reversing an array a; this does not change the original a
print("\na:",a) # original a is as it is.

# Boolean indexing
print("a[a<2]=>", a[a<=2]) # select element from a less than equal to 2.

# Fancy indexing 
print("b[[1, 0, 1, 0],[0,1,2,0]]=>", b[[1, 0, 1, 0],[0,1,2,0]]) # select elements (1,0), (0, 1), (1,2), (0,0)

a: [2 3 3] 

b: [[1.5 2.  3. ]
 [4.  5.  6. ]] 
c: [[[1.5 2.  1. ]
  [4.  5.  6. ]]

 [[3.  2.  3. ]
  [4.  5.  6. ]]]
3
6.0
6.0
[2 3]
[2. 5.]
b[:1]=> [[1.5 2.  3. ]]
[[3. 2. 3.]
 [4. 5. 6.]]
a[::-1]=> [3 3 2]

a: [2 3 3]
a[a<2]=> [2]
b[[1, 0, 1, 0],[0,1,2,0]]=> [4.  2.  6.  1.5]


### Array Manipulation

In [95]:
# Transposing array
i = np.transpose(b) # permute array dimensions
print("i:", i)
print(i.T) # Permute array dimensions ; gets the original b matrix

# Changing array shape
print(b.ravel()) # flatten the array ; this does not change the original b matrix
print("b:", b) # prints the same origina b matrix
print(b.reshape(3, -2)) # Reshape, but don't change data ; this does not change the original b value
print("b: ", b) # same b value

i: [[1.5 4. ]
 [2.  5. ]
 [3.  6. ]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[1.5 2.  3.  4.  5.  6. ]
b: [[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.5 2. ]
 [3.  4. ]
 [5.  6. ]]
b:  [[1.5 2.  3. ]
 [4.  5.  6. ]]


In [96]:
# Adding/Removing Elements
print("h:", h)
print(h.resize((2,6))) # does not return value; changes original h value
print(h) # this is now changed.

h: [3 2 3]
None
[[3 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [98]:
# np.append(h, g) # Append items to an array
# np.insert(a, 1, 5) # Insert items in an array
# np.delete(a[1]) # Delete items from an array

In [118]:



d = np.arange(10, 25, 5)
e = np.full((2,2), 7)
f = np.eye(2)
print("d:", d, "e:",e, "f:",f)
# Combining Arrays 
print(np.concatenate((a,d), axis=0)) # doesn't change original matrix a and d
print(a, d)

# using vstack and hstack
print("np.vstack((a,b))=>\n", np.vstack((a,b))) # stack array vertically (row-wise)
print("\nnp.hstack((a,b))=>\n", np.hstack((e,f))) # stack array horizontally (column wise)

# np.r_[e,f]
print("np.r_[e,f]=> ", np.r_[e,f])# stack arrays vertically row-wise.
print(np.c_[a,d]) # create stacked column-wise array; you have tow 1d array they are merged to create 2 columns

# column_stack
print("np.column_stack((a,d))=>\n", np.column_stack((a,d))) # create stacked column-wise array ; 
# gets value and creates column wise array


# Splitting
print("np.hsplit(a, 3)=>\n", np.hsplit(a, 3)) # Split the array a horizontally at index 3
#The value 3 has to split array in equal division otherwise it throws error. E.g.np.hsplit(a, 2)=>throws error.

print("np.vsplit(c,2)=>", np.vsplit(c,2)) # split the array vertically at the 2nd index

d: [10 15 20] e: [[7 7]
 [7 7]] f: [[1. 0.]
 [0. 1.]]
[ 2  3  3 10 15 20]
[2 3 3] [10 15 20]
np.vstack((a,b))=>
 [[2.  3.  3. ]
 [1.5 2.  3. ]
 [4.  5.  6. ]]

np.hstack((a,b))=>
 [[7. 7. 1. 0.]
 [7. 7. 0. 1.]]
np.r_[e,f]=>  [[7. 7.]
 [7. 7.]
 [1. 0.]
 [0. 1.]]
[[ 2 10]
 [ 3 15]
 [ 3 20]]
np.column_stack((a,d))=>
 [[ 2 10]
 [ 3 15]
 [ 3 20]]
np.hsplit(a, 3)=>
 [array([2]), array([3]), array([3])]
[array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
        [4., 5., 6.]]])]
